name: API deployment workflow
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: pwd
      - run: cd
      - run: cd mhirj-api
      - run: git status
      - run: git pull origin main
      #- run: pm2 restart mhirjApi